FirstWebApp/Controllers/GamesController.cs
using FirstWebApp.Extentions;
using FirstWebApp.Models;
using FirstWebApp.ServerDatabase;
using Microsoft.AspNetCore.Mvc;

namespace FirstWebApp.Controllers
{
    public class GamesController : Controller
    {
        Database dataBase;
        public GamesController(Database dataBase) 
        {
            this.dataBase = dataBase;
        }
        public IActionResult TicTacToe()
        {
            if (
                !this.CheckSessionExist(
                Session.SessionVariablesName.CurrentPlayerGuid |
                Session.SessionVariablesName.EncodedField |
                Session.SessionVariablesName.TableGuid)
            )
            {
                return RedirectToAction("SessionExpiration", "Home");
            }

            var currentPlayerGuid = this.GetCurrentPlayerGuidFromSession() ?? Guid.Empty;
            var tableGuid = this.GetTableGuidFromSession() ?? Guid.Empty;
            var gameInfo = this.GetCurrentGameInfo(tableGuid, dataBase);
            var model = new TicTacToeModel(gameInfo, currentPlayerGuid, dataBase);

            return View(model);
        }

        public IActionResult ObserverPage()
        {
            if (
                !this.CheckSessionExist(
                Session.SessionVariablesName.CurrentPlayerGuid |
                Session.SessionVariablesName.EncodedField |
                Session.SessionVariablesName.TableGuid)
            )
            {
                return RedirectToAction("SessionExpiration", "Home");
            }

            var currentPlayerGuid = this.GetCurrentPlayerGuidFromSession() ?? Guid.Empty;
            var tableGuid = this.GetTableGuidFromSession() ?? Guid.Empty;
            var gameInfo = this.GetCurrentGameInfo(tableGuid, dataBase);
            var model = new TicTacToeModel(gameInfo, currentPlayerGuid, dataBase);
            return View(model);
        }

        [HttpPost]
        public IActionResult Turn(int fieldIndex)
        {
            if (
                !this.CheckSessionExist(
                Session.SessionVariablesName.CurrentPlayerGuid |
                Session.SessionVariablesName.EncodedField |
                Session.SessionVariablesName.TableGuid)
            )
            {
                return RedirectToAction("SessionExpiration", "Home");
            }

            var currentPlayerGuid = this.GetCurrentPlayerGuidFromSession() ?? Guid.Empty;
            var tableGuid = this.GetTableGuidFromSession() ?? Guid.Empty;
            var gameInfo = this.GetCurrentGameInfo(tableGuid, dataBase);
            var model = new TicTacToeModel(gameInfo, currentPlayerGuid, dataBase);

            var encodedField = model.EncodedField;
            var field = Utilities.TicTacToeUtilities.DecodeField(encodedField);

            field[fieldIndex] = model.isPlayerXTurn ? 'X' : 'O';
            model.SetField(field);

            var gameGuid = dataBase.Tables[tableGuid] ?? Guid.Empty;
            dataBase.Games[gameGuid] = (GameInfo)model;

            if (model.isVictory)
            {
                return RedirectToAction("EndGame", "Home");
            }
            else
            {
                dataBase.Games[gameGuid].SetNextPlayerTurn();
                return RedirectToAction(nameof(TicTacToe));
            }
        }
    }
}

FirstWebApp/Views/Partial/FieldView.cshtml
@model FieldViewDataModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style>
    .TicTacToe-LobbyBoard {
        display: inline;
    }

	.turnForm {
		height: 100%;
       
    }

    .turnForm button{
    height: 100%;
        width: 100%;
            border: 0;
			padding: 0;
			background: inherit;
    }

</style>

<table class="TicTacToe-LobbyBoard">
    @for (int row = 0; row < 3; ++row)
    {
        <tr>
            @for (int col = 0; col < 3; ++col)
            {
                <td>
                    @{
                        var index = row * 3 + col;
                    }
                    @if (Model.IsReadOnlyView || Model.DecodedField[index] != ' ')
                    {
                        <span>
                        @Model.DecodedField[index]
                        </span>
                    }
                    else
                    {
                        <form class="turnForm" asp-controller="Games" asp-action="Turn">
                            @Html.Hidden("fieldIndex", index)
                            <button type="submit"> </button>
                        </form>
                    }
                </td>
            }
        </tr>
    }
</table>

FirstWebApp/Views/Partial/FieldViewForObserver.cshtml
@model FieldViewDataModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<script src="~/js/Ajax_UpdaterObserver.js"></script>

<script>
    SetUpdater()
</script>

<style>
    .TicTacToe-LobbyBoard {
        display: inline;
    }

    .turnForm {
        height: 100%;
    }

        .turnForm button {
            height: 100%;
            width: 100%;
            border: 0;
            padding: 0;
            background: inherit;
        }

</style>

<table class="TicTacToe-LobbyBoard">
    @for (int row = 0; row < 3; ++row)
    {
        <tr>
            @for (int col = 0; col < 3; ++col)
            {
                <td>
                    @{
                        var index = row * 3 + col;
                    }
                    @if (Model.IsReadOnlyView || Model.DecodedField[index] != ' ')
                    {
                        <span>
                            @Model.DecodedField[index]
                        </span>
                    }
                    else
                    {
                            <button class="turnForm"> </button>
                    }
                </td>
            }
        </tr>
    }
</table>

FirstWebApp/Views/Partial/LobbyTable.cshtml
@model LobbyTableModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
	.GameLobbyTable{
		width: 100%;
	}
    .TicTacToe-LobbyBoard{
        display: inline;
    }
</style>

<table class="GameLobbyTable">
    <tr>
        <td>
            X player: @Model.Game.PlayerXName
        </td>
    </tr>
    <tr>
        <td>
            O player: @Model.Game.PlayerOName
        </td>
    </tr>
    <tr>
        <td>
            Turn: Player (@Model.Game.CurrentTurnSimbol) | 
            Turn count: @Model.Game.turnCounter
        </td>
    </tr>
    <tr>
        <td>
            @await Html.PartialAsync("../Partial/FieldView", new FieldViewDataModel(Model.Game, true))
        </td>
    </tr>
    <tr>
        <td>
            <form method="post">
                <input type="hidden" name="tableGuid" value="@Model.TabelGuid"/>
                <input type="hidden" name="field" value="@Model.Game.EncodedField" />
				<button asp-controller="Home" asp-action="GoToGame">Зайти на хату</button>
            </form>
        </td>
    </tr>
</table>